import { writeFile } from 'node:fs/promises';
import path from 'node:path';
import { appRoot, collectLibrary } from './library-data.mjs';
const outputPath = path.join(appRoot, 'app', 'library.generated.ts');
const documents = await collectLibrary();

const source = `// Generated by scripts/sync-library.mjs. Do not edit by hand.\nexport type LibraryDocument = { id: string; book: string; chapterId: string; chapterNumber: number; chapterTitle: string; title: string; variant: string; preferred: boolean; batchCount: number; content: string };\nexport const library: LibraryDocument[] = ${JSON.stringify(documents, null, 2)};\n`;
await writeFile(outputPath, source, 'utf8');
console.log(`Synced ${documents.length} assembled reading documents.`);
