import { readdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const appRoot = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const booksRoot = path.resolve(appRoot, '..', 'books');
const outputPath = path.join(appRoot, 'app', 'library.generated.ts');

async function directories(parent) {
  return (await readdir(parent, { withFileTypes: true }))
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name);
}

const documents = [];
for (const book of await directories(booksRoot)) {
  const chaptersRoot = path.join(booksRoot, book, 'chapters');
  for (const chapterId of await directories(chaptersRoot)) {
    if (!/^ch\d+$/i.test(chapterId)) continue;
    const chapterRoot = path.join(chaptersRoot, chapterId);
    const files = (await readdir(chapterRoot))
      .filter((name) => /^\d+_.+\.md$/i.test(name))
      .sort((a, b) => a.localeCompare(b, 'zh-CN'));
    for (const file of files) {
      const content = await readFile(path.join(chapterRoot, file), 'utf8');
      const number = Number(chapterId.replace(/\D/g, ''));
      documents.push({
        id: `${book}/${chapterId}/${file}`,
        book,
        chapterId,
        chapterNumber: number,
        chapterTitle: `第 ${number} 章`,
        title: content.match(/^#\s+(.+)$/m)?.[1]?.trim() || `${book} · 第 ${number} 章`,
        variant: file.replace(/^\d+_/, '').replace(/\.md$/i, ''),
        preferred: /易读|意译/.test(file),
        content,
      });
    }
  }
}
documents.sort((a, b) => a.book.localeCompare(b.book, 'zh-CN') || a.chapterNumber - b.chapterNumber || a.id.localeCompare(b.id, 'zh-CN'));

const source = `// Generated by scripts/sync-library.mjs. Do not edit by hand.\nexport type LibraryDocument = { id: string; book: string; chapterId: string; chapterNumber: number; chapterTitle: string; title: string; variant: string; preferred: boolean; content: string };\nexport const library: LibraryDocument[] = ${JSON.stringify(documents, null, 2)};\n`;
await writeFile(outputPath, source, 'utf8');
console.log(`Synced ${documents.length} reading documents.`);
